version: '3.8'
services:
  web:
    image: mp4-to-gif-frontend
    ports:
      - "8080:80"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure

  api:
    build: .
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
      restart_policy:
        condition: on-failure