version: '3.8'
services:
  web:
    image: mp4-to-gif-frontend
    ports:
      - "8080:80"
    deploy:
      replicas: 1
  api:
    image: mp4-to-gif-backend
    ports:
      - "3000:3000"
    deploy:
      replicas: 5