version: '3.8'

services:
  web:
    build:
      context: ./client.
      dockerfile: Dockerfile
    ports:
      - "80:80"
    deploy:
      replicas: 1 

  api:
    build:
      context: ./server.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    deploy:
      replicas: 5  